version: '3'
services:
  pyflora_flask:
    build:
      context: ./flaskr
      dockerfile: Dockerfile_flask
    ports:
      - '5000:5000'
    volumes:
      - ../PyFlora:/PyFlora

  fake_raspberry_api:
    build:
      context: ./app
      dockerfile: Dockerfile_API
    ports:
      - '80:80'
    volumes:
    - ./app:/app