version: '3'
services:
  pyflora_flask:
    build:
      context: ./flaskr
      dockerfile: Dockerfile_flask
    ports:
      - '5000:5000'

  fake_raspberry_api:
    build:
      context: ./api
      dockerfile: Dockerfile_API
    ports:
      - '80:80'
