# syntax=docker/dockerfile:1
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app

# Set the environment variable for the API
ENV VARIABLE_NAME=main.py

# Expose port 80 for the API
EXPOSE 80

# Run the command to start the API server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]